name: Run tests and deploy if release tag

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Deploy
        if: success()
        env:
          LABORATORIA_API_EMAIL: ${{ secrets.LABORATORIA_API_EMAIL }}
          LABORATORIA_API_PASS: ${{ secrets.LABORATORIA_API_PASS }}
        run: npm run deploy

  deploy_to_staging:
    runs-on: ubuntu-latest
    if: >
      startsWith(github.ref, 'refs/tags/v')
      && (
        contains(github.ref, 'alpha')
        || contains(github.ref, 'beta')
      )
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
        env:
          REACT_APP_LABORATORIA_API_URL: https://api.laboratoria.la
          REACT_APP_FIREBASE_API_KEY: AIzaSyAXbaEbpq8NOfn0r8mIrcoHvoGRkJThwdc 
          REACT_APP_FIREBASE_PROJECT: laboratoria-la
          REACT_APP_VERSION: $npm_package_version
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOOTCAMP_E078F }}"
          channelId: staging
          expires: 30d
          projectId: bootcamp-e078f

  deploy_to_production:
    runs-on: ubuntu-latest
    if: >
      startsWith(github.ref, 'refs/tags/v')
      && !contains(github.ref, 'alpha')
      && !contains(github.ref, 'beta')
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
        env:
          REACT_APP_LABORATORIA_API_URL: https://api.laboratoria.la
          REACT_APP_FIREBASE_API_KEY: AIzaSyAXbaEbpq8NOfn0r8mIrcoHvoGRkJThwdc 
          REACT_APP_FIREBASE_PROJECT: laboratoria-la
          REACT_APP_VERSION: $npm_package_version
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOOTCAMP_E078F }}"
          channelId: live
          projectId: bootcamp-e078f